# Generated by Django 5.1.3 on 2024-11-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0002_rename_user_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='User',
        ),
    ]
